[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración de funciones y redirecciones
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
